services:
  - type: web
    name: worshiptool
    runtime: python
    plan: free
    buildCommand: bash build.sh
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    nativePackages:
      - tesseract-ocr
      - tesseract-ocr-khm
      - poppler-utils
      - libgl1
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
